//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaniloRamos_TechExam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecyclableType
    {
        public int id { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> MinKg { get; set; }
        public Nullable<decimal> MaxKg { get; set; }
    }
}
